// flow-typed signature: e46b43f9fcc48ae86f238854b07696d5
// flow-typed version: <<STUB>>/electron-rebuild_v^3.2.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-rebuild'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-rebuild' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-rebuild/lib/src/arch' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/cache' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/clang-fetcher' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/cli' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/constants' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/electron-locator' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/fetcher' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/module-rebuilder' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/module-type/index' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/module-type/node-gyp' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/module-type/prebuild-install' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/module-type/prebuildify' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/node-api' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/prebuild-shim' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/rebuild' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/search-module' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/sysroot-fetcher' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/arch' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/electron-locator' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/helpers/electron-version' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/helpers/module-setup' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/helpers/rebuild' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/module-type-prebuild-install' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/module-type-prebuildify' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/rebuild-yarnworkspace' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/rebuild' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/test/search-module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-rebuild/lib/src/arch.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/arch'>;
}
declare module 'electron-rebuild/lib/src/cache.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/cache'>;
}
declare module 'electron-rebuild/lib/src/clang-fetcher.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/clang-fetcher'>;
}
declare module 'electron-rebuild/lib/src/cli.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/cli'>;
}
declare module 'electron-rebuild/lib/src/constants.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/constants'>;
}
declare module 'electron-rebuild/lib/src/electron-locator.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/electron-locator'>;
}
declare module 'electron-rebuild/lib/src/fetcher.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/fetcher'>;
}
declare module 'electron-rebuild/lib/src/main.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/main'>;
}
declare module 'electron-rebuild/lib/src/module-rebuilder.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/module-rebuilder'>;
}
declare module 'electron-rebuild/lib/src/module-type/index.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/module-type/index'>;
}
declare module 'electron-rebuild/lib/src/module-type/node-gyp.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/module-type/node-gyp'>;
}
declare module 'electron-rebuild/lib/src/module-type/prebuild-install.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/module-type/prebuild-install'>;
}
declare module 'electron-rebuild/lib/src/module-type/prebuildify.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/module-type/prebuildify'>;
}
declare module 'electron-rebuild/lib/src/node-api.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/node-api'>;
}
declare module 'electron-rebuild/lib/src/prebuild-shim.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/prebuild-shim'>;
}
declare module 'electron-rebuild/lib/src/read-package-json.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/read-package-json'>;
}
declare module 'electron-rebuild/lib/src/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/rebuild'>;
}
declare module 'electron-rebuild/lib/src/search-module.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/search-module'>;
}
declare module 'electron-rebuild/lib/src/sysroot-fetcher.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/sysroot-fetcher'>;
}
declare module 'electron-rebuild/lib/test/arch.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/arch'>;
}
declare module 'electron-rebuild/lib/test/electron-locator.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/electron-locator'>;
}
declare module 'electron-rebuild/lib/test/helpers/electron-version.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/helpers/electron-version'>;
}
declare module 'electron-rebuild/lib/test/helpers/module-setup.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/helpers/module-setup'>;
}
declare module 'electron-rebuild/lib/test/helpers/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/helpers/rebuild'>;
}
declare module 'electron-rebuild/lib/test/module-type-prebuild-install.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/module-type-prebuild-install'>;
}
declare module 'electron-rebuild/lib/test/module-type-prebuildify.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/module-type-prebuildify'>;
}
declare module 'electron-rebuild/lib/test/read-package-json.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/read-package-json'>;
}
declare module 'electron-rebuild/lib/test/rebuild-yarnworkspace.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/rebuild-yarnworkspace'>;
}
declare module 'electron-rebuild/lib/test/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/rebuild'>;
}
declare module 'electron-rebuild/lib/test/search-module.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/test/search-module'>;
}
