// flow-typed signature: 2db04d8d6803e9ce196501aaed12d8c7
// flow-typed version: <<STUB>>/ip-regex_v^3.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ip-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ip-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ip-regex/index' {
  declare module.exports: $Exports<'ip-regex'>;
}
declare module 'ip-regex/index.js' {
  declare module.exports: $Exports<'ip-regex'>;
}
