// flow-typed signature: 22dda4443b65e125168253ffcafa1670
// flow-typed version: <<STUB>>/screenshot-desktop_v^1.5.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'screenshot-desktop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'screenshot-desktop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'screenshot-desktop/example' {
  declare module.exports: any;
}

declare module 'screenshot-desktop/lib/darwin/index' {
  declare module.exports: any;
}

declare module 'screenshot-desktop/lib/linux/index' {
  declare module.exports: any;
}

declare module 'screenshot-desktop/lib/utils' {
  declare module.exports: any;
}

declare module 'screenshot-desktop/lib/win32/index' {
  declare module.exports: any;
}

declare module 'screenshot-desktop/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'screenshot-desktop/example.js' {
  declare module.exports: $Exports<'screenshot-desktop/example'>;
}
declare module 'screenshot-desktop/index' {
  declare module.exports: $Exports<'screenshot-desktop'>;
}
declare module 'screenshot-desktop/index.js' {
  declare module.exports: $Exports<'screenshot-desktop'>;
}
declare module 'screenshot-desktop/lib/darwin/index.js' {
  declare module.exports: $Exports<'screenshot-desktop/lib/darwin/index'>;
}
declare module 'screenshot-desktop/lib/linux/index.js' {
  declare module.exports: $Exports<'screenshot-desktop/lib/linux/index'>;
}
declare module 'screenshot-desktop/lib/utils.js' {
  declare module.exports: $Exports<'screenshot-desktop/lib/utils'>;
}
declare module 'screenshot-desktop/lib/win32/index.js' {
  declare module.exports: $Exports<'screenshot-desktop/lib/win32/index'>;
}
declare module 'screenshot-desktop/test.js' {
  declare module.exports: $Exports<'screenshot-desktop/test'>;
}
